# Non Graded Challenge 5

`Dicky Librata Sembiring`\
`Hactive8 Student`\
`FTDS Batch 003` 

### Objective
Pada Non Graded Challenge berikut berisi :
1. Cara membuat Tensor dengan python
2. Perkalian Matrix dengan Matrix
3. Transpose, Determinan, Dan Inverse Matrix

#### Import Pustaka

In [2]:
import numpy as np

#### Soal No 1

In [3]:
# Buat tensor
tensor = np.array([
    [[23,50],[7,12]],
    [[57,67],[99,43]],
    [[75,21],[57,12]],
    [[87,26],[18,84]]])

tensor

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

#### Soal No 2

In [4]:
# Buat matrix
A = np.array([[23,50,19], [7,12,109],[57,67,98]])
B = np.array([[17],[22],[19]])

In [5]:
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [6]:
B

array([[17],
       [22],
       [19]])

Perkalian Matrix

In [7]:
C = A.dot(B)
C

array([[1852],
       [2454],
       [4305]])

#### Soal No 3

In [8]:
A2 = np.array([[23,50,19], [7,12,19],[57,67,98]])
A2

array([[23, 50, 19],
       [ 7, 12, 19],
       [57, 67, 98]])

In [9]:
A2.transpose()

array([[23,  7, 57],
       [50, 12, 67],
       [19, 19, 98]])

In [10]:
np.linalg.det(A2)

13534.0

In [11]:
np.linalg.inv(A2)

array([[-0.00716713, -0.26799172,  0.05334713],
       [ 0.02933353,  0.08652283, -0.02246195],
       [-0.01588592,  0.09671937, -0.00546771]])